// Generated by Leapkit, do not edit this file
// Leapkit took the files in the public folder and
// embedded those to be available in the binary.
package public

import (
	"embed"
)

var (
	// publicFolder is a mdfs instance that contains all the
	// files in the public folder.
	Files = embed.FS{}
)
